# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Optimization configuration

---
n_epoch: 7
main_args:
    lr: 0.0001
    opt_args: [0.9, 0.999, 0]
    schedule_args: ['multistep', 2, 4, 0.1]
loss_args:
    loss: ce_sparse
    alpha: 0
    beta: 0
clip_max_norm: -1
